name: narrativa
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  geocoding: ^3.0.0
  go_router: ^14.8.1
  google_maps_flutter: ^2.12.1
  image_picker: ^1.1.2
  jiffy: ^6.4.3
  json_annotation: ^4.9.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/
